name: Update proxies
on:
  schedule:
    - cron: "* * * * *"
  workflow_dispatch:
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: "Checkout repo"
        uses: actions/checkout@v2
        with:
          fetch-depth: 1
      - name: "Checkout monosans/proxy-scraper-checker"
        uses: actions/checkout@v2
        with:
          repository: monosans/proxy-scraper-checker
          path: proxy-scraper-checker
          fetch-depth: 1
      - name: "Setup Python"
        uses: actions/setup-python@v2
        with:
          python-version: 3.9
      - name: "Install dependencies"
        run: |
          python -m pip install -U pip setuptools wheel
          python -m pip install -r proxy-scraper-checker/requirements.txt
      - name: "Run proxy-scraper-checker"
        run: |
          cd proxy-scraper-checker
          sed -i "s/TIMEOUT = 5/TIMEOUT = 10/" config.py
          sed -i "s/ident.me/checkip.amazonaws.com/" config.py
          python main.py
      - name: "Move new proxies"
        run: |
          rm -rf proxies*
          mv proxy-scraper-checker/proxies* .
          rm -rf proxy-scraper-checker     
      - name: Commit
        run: |
          git config user.name "${GITHUB_ACTOR}"
          git config user.email "${GITHUB_ACTOR}@users.noreply.github.com"
          git add .
          git commit -am "Update File"
          git push --all -f https://${{ secrets.GITHUB_TOKEN }}@github.com/${GITHUB_REPOSITORY}.git 
